spring:
  application:
    name: Digitalisation_Processus_Recrutement
  db1:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/db1_processus_recrutement?createDatabaseIfNotExist=true&useSSL=false  # Update URL for MySQL
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver  # Update driver class for MySQL
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create  # Keep your existing settings
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
  db2:
    datasource:
      jdbc-url: jdbc:oracle:thin:@192.168.99.154:15212:HPRD
      username: RECRUTEMENT
      password: WydQyC*5XUmJ9x
      driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
      properties:
        hibernate:
          ddl-auto: none
          show_sql: true
  jpa:
    generate-ddl: true

#spring:
#  application:
#    name: Digitalisation_Processus_Recrutement
#  datasource:
#    url: jdbc:sqlserver://alias_sql_prd.cofarma.co.ma:1433;encrypt=true;trustServerCertificate=true;databaseName=HRRecrutement  # URL pour la base de données SQL Server  # Mettez à jour l'URL avec les informations de votre base de données SQL Server
#    username: userhr
#    password: GhTQkNEYjM
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  # Utilisez le pilote JDBC SQL Server
#  jpa:
#    hibernate:
#      ddl-auto: update  # Conservez vos paramètres existants
#    show-sql: true  # Conservez vos paramètres existants
#    properties:
#      hibernate:
#        format_sql: true  # Conservez vos paramètres existants
#    database: sql_server  # Mettez à jour le type de base de données en SQL Server
#    database-platform: org.hibernate.dialect.SQLServerDialect  # Utilisez le dialecte SQL Server
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
  port: 8080

upload:
  dir: ./uploads
